version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_local
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    command:
      --local-infile=1
      --secure-file-priv=""
      --max_allowed_packet=512M
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./data_csv:/data_csv

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-local
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "7333:80"
